version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8.12.0

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build

  test:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm run test:ci

workflows:
  version: 2

  test:
    jobs:
      - setup
      - test:
          requires:
            - setup
