version: 2

references:
  defaults: &defaults
    working_directory: ~/project/seed

  node_image: &node_image
    circleci/node:8-browsers

  gcloud_image: &gcloud_image
    google/cloud-sdk

  persist_to_workspace: &persist_to_workspace
    - persist_to_workspace:
        root: ~/project
        paths:
          - seed

  attach_workspace: &attach_workspace
    - attach_workspace:
          at: ~/project

jobs:
  install:
    <<: *defaults
    docker:
      - image: *node_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ .Branch }}-
            - v1-npm-deps-
      - run:
          name: Install Depependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist_to_workspace

  test:
    <<: *defaults
    docker:
      - image: *node_image
    steps:
      - *attach_workspace
      - run:
          name: Type Check
          command: npm run typecheck
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci

  build:
    <<: *defaults
    docker:
      - image: *node_image
    steps:
      - *attach_workspace
      - run:
          name: Build Production
          command: npm run build:production
      - *persist_to_workspace

  deploy:
    <<: *defaults
    docker:
      - image: *gcloud_image
    steps:
      - *attach_workspace
      - run:
          name: Activate Service Account
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run:
          name: Configure the Google Cloud SDK
          command: |
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_COMPUTE_ZONE}
      - run:
          name: Deploy to App Engine
          command: gcloud app deploy --quiet

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
