version: 2

references:
  defaults: &defaults
    working_directory: ~/project/seed
    docker:
      - image: circleci/node:8-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-npm-deps-{{ .Branch }}-
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - seed

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test:ci

workflows:
  version: 2

  install_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
