version: 2

references:
  container_config: &container_config
    docker:
    - image: circleci/node:8.11.3

  restore_npm: &restore_npm
    restore_cache:
      key: node-{{ checksum "package.json" }}
      paths:
        - node_modules

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *restore_npm
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: node-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: dist
          paths:
            - .

  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_npm
      - attach_workspace:
          at: dist
      - run:
          name: Test
          command: npm run test:ci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
