export const register = () => {
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () => {
      // Generated by workbox-webpack-plugin
      // https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin
      navigator.serviceWorker.register("/service-worker.js");
    });
  }
};

export const unregister = async () => {
  if ("serviceWorker" in navigator) {
    const registrations = await navigator.serviceWorker.getRegistrations();

    for (const registration of registrations) {
      registration.unregister();
    }
  }
};
